// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: pkg/bridge/bridge.proto

package bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotService_GetNodeSnapshot_FullMethodName   = "/bridge.SnapshotService/GetNodeSnapshot"
	SnapshotService_ClearNodeSnapshot_FullMethodName = "/bridge.SnapshotService/ClearNodeSnapshot"
)

// SnapshotServiceClient is the client API for SnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotServiceClient interface {
	GetNodeSnapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*NodeSnapshotResponse, error)
	ClearNodeSnapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*ClearSnapshotResponse, error)
}

type snapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotServiceClient(cc grpc.ClientConnInterface) SnapshotServiceClient {
	return &snapshotServiceClient{cc}
}

func (c *snapshotServiceClient) GetNodeSnapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*NodeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_GetNodeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) ClearNodeSnapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*ClearSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_ClearNodeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServiceServer is the server API for SnapshotService service.
// All implementations must embed UnimplementedSnapshotServiceServer
// for forward compatibility.
type SnapshotServiceServer interface {
	GetNodeSnapshot(context.Context, *NodeSnapshotRequest) (*NodeSnapshotResponse, error)
	ClearNodeSnapshot(context.Context, *NodeSnapshotRequest) (*ClearSnapshotResponse, error)
	mustEmbedUnimplementedSnapshotServiceServer()
}

// UnimplementedSnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotServiceServer struct{}

func (UnimplementedSnapshotServiceServer) GetNodeSnapshot(context.Context, *NodeSnapshotRequest) (*NodeSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) ClearNodeSnapshot(context.Context, *NodeSnapshotRequest) (*ClearSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearNodeSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) mustEmbedUnimplementedSnapshotServiceServer() {}
func (UnimplementedSnapshotServiceServer) testEmbeddedByValue()                         {}

// UnsafeSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotServiceServer will
// result in compilation errors.
type UnsafeSnapshotServiceServer interface {
	mustEmbedUnimplementedSnapshotServiceServer()
}

func RegisterSnapshotServiceServer(s grpc.ServiceRegistrar, srv SnapshotServiceServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotService_ServiceDesc, srv)
}

func _SnapshotService_GetNodeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).GetNodeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_GetNodeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).GetNodeSnapshot(ctx, req.(*NodeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_ClearNodeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).ClearNodeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_ClearNodeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).ClearNodeSnapshot(ctx, req.(*NodeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotService_ServiceDesc is the grpc.ServiceDesc for SnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.SnapshotService",
	HandlerType: (*SnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeSnapshot",
			Handler:    _SnapshotService_GetNodeSnapshot_Handler,
		},
		{
			MethodName: "ClearNodeSnapshot",
			Handler:    _SnapshotService_ClearNodeSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/bridge.proto",
}

const (
	PokeService_Poke_FullMethodName           = "/bridge.PokeService/Poke"
	PokeService_NotifyUndeploy_FullMethodName = "/bridge.PokeService/NotifyUndeploy"
)

// PokeServiceClient is the client API for PokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokeServiceClient interface {
	Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error)
	NotifyUndeploy(ctx context.Context, in *UndeployRequest, opts ...grpc.CallOption) (*UndeployResponse, error)
}

type pokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPokeServiceClient(cc grpc.ClientConnInterface) PokeServiceClient {
	return &pokeServiceClient{cc}
}

func (c *pokeServiceClient) Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokeResponse)
	err := c.cc.Invoke(ctx, PokeService_Poke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokeServiceClient) NotifyUndeploy(ctx context.Context, in *UndeployRequest, opts ...grpc.CallOption) (*UndeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeployResponse)
	err := c.cc.Invoke(ctx, PokeService_NotifyUndeploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokeServiceServer is the server API for PokeService service.
// All implementations must embed UnimplementedPokeServiceServer
// for forward compatibility.
type PokeServiceServer interface {
	Poke(context.Context, *PokeRequest) (*PokeResponse, error)
	NotifyUndeploy(context.Context, *UndeployRequest) (*UndeployResponse, error)
	mustEmbedUnimplementedPokeServiceServer()
}

// UnimplementedPokeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokeServiceServer struct{}

func (UnimplementedPokeServiceServer) Poke(context.Context, *PokeRequest) (*PokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poke not implemented")
}
func (UnimplementedPokeServiceServer) NotifyUndeploy(context.Context, *UndeployRequest) (*UndeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUndeploy not implemented")
}
func (UnimplementedPokeServiceServer) mustEmbedUnimplementedPokeServiceServer() {}
func (UnimplementedPokeServiceServer) testEmbeddedByValue()                     {}

// UnsafePokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokeServiceServer will
// result in compilation errors.
type UnsafePokeServiceServer interface {
	mustEmbedUnimplementedPokeServiceServer()
}

func RegisterPokeServiceServer(s grpc.ServiceRegistrar, srv PokeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokeService_ServiceDesc, srv)
}

func _PokeService_Poke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokeServiceServer).Poke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokeService_Poke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokeServiceServer).Poke(ctx, req.(*PokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokeService_NotifyUndeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokeServiceServer).NotifyUndeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokeService_NotifyUndeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokeServiceServer).NotifyUndeploy(ctx, req.(*UndeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokeService_ServiceDesc is the grpc.ServiceDesc for PokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.PokeService",
	HandlerType: (*PokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poke",
			Handler:    _PokeService_Poke_Handler,
		},
		{
			MethodName: "NotifyUndeploy",
			Handler:    _PokeService_NotifyUndeploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/bridge.proto",
}

const (
	ResourceService_ValidateResource_FullMethodName = "/bridge.ResourceService/ValidateResource"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	ValidateResource(ctx context.Context, in *ValidateResourceRequest, opts ...grpc.CallOption) (*ValidateResourceResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) ValidateResource(ctx context.Context, in *ValidateResourceRequest, opts ...grpc.CallOption) (*ValidateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResourceResponse)
	err := c.cc.Invoke(ctx, ResourceService_ValidateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
type ResourceServiceServer interface {
	ValidateResource(context.Context, *ValidateResourceRequest) (*ValidateResourceResponse, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) ValidateResource(context.Context, *ValidateResourceRequest) (*ValidateResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateResource not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_ValidateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ValidateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ValidateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ValidateResource(ctx, req.(*ValidateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateResource",
			Handler:    _ResourceService_ValidateResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/bridge.proto",
}
