// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: pkg/bridge/registry.proto

package bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerRoutingService_RegisterController_FullMethodName       = "/bridge.ControllerRoutingService/RegisterController"
	ControllerRoutingService_GetControllerCluster_FullMethodName     = "/bridge.ControllerRoutingService/GetControllerCluster"
	ControllerRoutingService_NotifyClientConnected_FullMethodName    = "/bridge.ControllerRoutingService/NotifyClientConnected"
	ControllerRoutingService_UpdateClientList_FullMethodName         = "/bridge.ControllerRoutingService/UpdateClientList"
	ControllerRoutingService_ListControllers_FullMethodName          = "/bridge.ControllerRoutingService/ListControllers"
	ControllerRoutingService_ListClientsByController_FullMethodName  = "/bridge.ControllerRoutingService/ListClientsByController"
	ControllerRoutingService_GetAllRegistryData_FullMethodName       = "/bridge.ControllerRoutingService/GetAllRegistryData"
	ControllerRoutingService_HealthCheck_FullMethodName              = "/bridge.ControllerRoutingService/HealthCheck"
	ControllerRoutingService_NotifyClientDisconnected_FullMethodName = "/bridge.ControllerRoutingService/NotifyClientDisconnected"
	ControllerRoutingService_DeleteController_FullMethodName         = "/bridge.ControllerRoutingService/DeleteController"
)

// ControllerRoutingServiceClient is the client API for ControllerRoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Controller Routing Service
type ControllerRoutingServiceClient interface {
	RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerResponse, error)
	GetControllerCluster(ctx context.Context, in *GetControllerClusterRequest, opts ...grpc.CallOption) (*GetControllerClusterResponse, error)
	// Controller client'ı aldı notification
	NotifyClientConnected(ctx context.Context, in *NotifyClientConnectedRequest, opts ...grpc.CallOption) (*NotifyClientConnectedResponse, error)
	// Bulk client update (30sn'de bir)
	UpdateClientList(ctx context.Context, in *UpdateClientListRequest, opts ...grpc.CallOption) (*UpdateClientListResponse, error)
	// List all controllers
	ListControllers(ctx context.Context, in *ListControllersRequest, opts ...grpc.CallOption) (*ListControllersResponse, error)
	// List clients by controller
	ListClientsByController(ctx context.Context, in *ListClientsByControllerRequest, opts ...grpc.CallOption) (*ListClientsByControllerResponse, error)
	// Get all registry data for reporting
	GetAllRegistryData(ctx context.Context, in *GetAllControllerRegistryDataRequest, opts ...grpc.CallOption) (*GetAllControllerRegistryDataResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *ControllerHealthCheckRequest, opts ...grpc.CallOption) (*ControllerHealthCheckResponse, error)
	NotifyClientDisconnected(ctx context.Context, in *NotifyClientDisconnectedRequest, opts ...grpc.CallOption) (*NotifyClientDisconnectedResponse, error)
	// Delete controller
	DeleteController(ctx context.Context, in *DeleteControllerRequest, opts ...grpc.CallOption) (*DeleteControllerResponse, error)
}

type controllerRoutingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerRoutingServiceClient(cc grpc.ClientConnInterface) ControllerRoutingServiceClient {
	return &controllerRoutingServiceClient{cc}
}

func (c *controllerRoutingServiceClient) RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterControllerResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_RegisterController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) GetControllerCluster(ctx context.Context, in *GetControllerClusterRequest, opts ...grpc.CallOption) (*GetControllerClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetControllerClusterResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_GetControllerCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) NotifyClientConnected(ctx context.Context, in *NotifyClientConnectedRequest, opts ...grpc.CallOption) (*NotifyClientConnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyClientConnectedResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_NotifyClientConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) UpdateClientList(ctx context.Context, in *UpdateClientListRequest, opts ...grpc.CallOption) (*UpdateClientListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClientListResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_UpdateClientList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) ListControllers(ctx context.Context, in *ListControllersRequest, opts ...grpc.CallOption) (*ListControllersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListControllersResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_ListControllers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) ListClientsByController(ctx context.Context, in *ListClientsByControllerRequest, opts ...grpc.CallOption) (*ListClientsByControllerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsByControllerResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_ListClientsByController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) GetAllRegistryData(ctx context.Context, in *GetAllControllerRegistryDataRequest, opts ...grpc.CallOption) (*GetAllControllerRegistryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllControllerRegistryDataResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_GetAllRegistryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) HealthCheck(ctx context.Context, in *ControllerHealthCheckRequest, opts ...grpc.CallOption) (*ControllerHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControllerHealthCheckResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) NotifyClientDisconnected(ctx context.Context, in *NotifyClientDisconnectedRequest, opts ...grpc.CallOption) (*NotifyClientDisconnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyClientDisconnectedResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_NotifyClientDisconnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRoutingServiceClient) DeleteController(ctx context.Context, in *DeleteControllerRequest, opts ...grpc.CallOption) (*DeleteControllerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteControllerResponse)
	err := c.cc.Invoke(ctx, ControllerRoutingService_DeleteController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerRoutingServiceServer is the server API for ControllerRoutingService service.
// All implementations must embed UnimplementedControllerRoutingServiceServer
// for forward compatibility.
//
// Controller Routing Service
type ControllerRoutingServiceServer interface {
	RegisterController(context.Context, *RegisterControllerRequest) (*RegisterControllerResponse, error)
	GetControllerCluster(context.Context, *GetControllerClusterRequest) (*GetControllerClusterResponse, error)
	// Controller client'ı aldı notification
	NotifyClientConnected(context.Context, *NotifyClientConnectedRequest) (*NotifyClientConnectedResponse, error)
	// Bulk client update (30sn'de bir)
	UpdateClientList(context.Context, *UpdateClientListRequest) (*UpdateClientListResponse, error)
	// List all controllers
	ListControllers(context.Context, *ListControllersRequest) (*ListControllersResponse, error)
	// List clients by controller
	ListClientsByController(context.Context, *ListClientsByControllerRequest) (*ListClientsByControllerResponse, error)
	// Get all registry data for reporting
	GetAllRegistryData(context.Context, *GetAllControllerRegistryDataRequest) (*GetAllControllerRegistryDataResponse, error)
	// Health check
	HealthCheck(context.Context, *ControllerHealthCheckRequest) (*ControllerHealthCheckResponse, error)
	NotifyClientDisconnected(context.Context, *NotifyClientDisconnectedRequest) (*NotifyClientDisconnectedResponse, error)
	// Delete controller
	DeleteController(context.Context, *DeleteControllerRequest) (*DeleteControllerResponse, error)
	mustEmbedUnimplementedControllerRoutingServiceServer()
}

// UnimplementedControllerRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerRoutingServiceServer struct{}

func (UnimplementedControllerRoutingServiceServer) RegisterController(context.Context, *RegisterControllerRequest) (*RegisterControllerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterController not implemented")
}
func (UnimplementedControllerRoutingServiceServer) GetControllerCluster(context.Context, *GetControllerClusterRequest) (*GetControllerClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControllerCluster not implemented")
}
func (UnimplementedControllerRoutingServiceServer) NotifyClientConnected(context.Context, *NotifyClientConnectedRequest) (*NotifyClientConnectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyClientConnected not implemented")
}
func (UnimplementedControllerRoutingServiceServer) UpdateClientList(context.Context, *UpdateClientListRequest) (*UpdateClientListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientList not implemented")
}
func (UnimplementedControllerRoutingServiceServer) ListControllers(context.Context, *ListControllersRequest) (*ListControllersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListControllers not implemented")
}
func (UnimplementedControllerRoutingServiceServer) ListClientsByController(context.Context, *ListClientsByControllerRequest) (*ListClientsByControllerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClientsByController not implemented")
}
func (UnimplementedControllerRoutingServiceServer) GetAllRegistryData(context.Context, *GetAllControllerRegistryDataRequest) (*GetAllControllerRegistryDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRegistryData not implemented")
}
func (UnimplementedControllerRoutingServiceServer) HealthCheck(context.Context, *ControllerHealthCheckRequest) (*ControllerHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedControllerRoutingServiceServer) NotifyClientDisconnected(context.Context, *NotifyClientDisconnectedRequest) (*NotifyClientDisconnectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyClientDisconnected not implemented")
}
func (UnimplementedControllerRoutingServiceServer) DeleteController(context.Context, *DeleteControllerRequest) (*DeleteControllerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteController not implemented")
}
func (UnimplementedControllerRoutingServiceServer) mustEmbedUnimplementedControllerRoutingServiceServer() {
}
func (UnimplementedControllerRoutingServiceServer) testEmbeddedByValue() {}

// UnsafeControllerRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerRoutingServiceServer will
// result in compilation errors.
type UnsafeControllerRoutingServiceServer interface {
	mustEmbedUnimplementedControllerRoutingServiceServer()
}

func RegisterControllerRoutingServiceServer(s grpc.ServiceRegistrar, srv ControllerRoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerRoutingService_ServiceDesc, srv)
}

func _ControllerRoutingService_RegisterController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).RegisterController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_RegisterController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).RegisterController(ctx, req.(*RegisterControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_GetControllerCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetControllerClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).GetControllerCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_GetControllerCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).GetControllerCluster(ctx, req.(*GetControllerClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_NotifyClientConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyClientConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).NotifyClientConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_NotifyClientConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).NotifyClientConnected(ctx, req.(*NotifyClientConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_UpdateClientList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).UpdateClientList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_UpdateClientList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).UpdateClientList(ctx, req.(*UpdateClientListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_ListControllers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListControllersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).ListControllers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_ListControllers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).ListControllers(ctx, req.(*ListControllersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_ListClientsByController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsByControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).ListClientsByController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_ListClientsByController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).ListClientsByController(ctx, req.(*ListClientsByControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_GetAllRegistryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllControllerRegistryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).GetAllRegistryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_GetAllRegistryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).GetAllRegistryData(ctx, req.(*GetAllControllerRegistryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).HealthCheck(ctx, req.(*ControllerHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_NotifyClientDisconnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyClientDisconnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).NotifyClientDisconnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_NotifyClientDisconnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).NotifyClientDisconnected(ctx, req.(*NotifyClientDisconnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRoutingService_DeleteController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRoutingServiceServer).DeleteController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRoutingService_DeleteController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRoutingServiceServer).DeleteController(ctx, req.(*DeleteControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerRoutingService_ServiceDesc is the grpc.ServiceDesc for ControllerRoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerRoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.ControllerRoutingService",
	HandlerType: (*ControllerRoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterController",
			Handler:    _ControllerRoutingService_RegisterController_Handler,
		},
		{
			MethodName: "GetControllerCluster",
			Handler:    _ControllerRoutingService_GetControllerCluster_Handler,
		},
		{
			MethodName: "NotifyClientConnected",
			Handler:    _ControllerRoutingService_NotifyClientConnected_Handler,
		},
		{
			MethodName: "UpdateClientList",
			Handler:    _ControllerRoutingService_UpdateClientList_Handler,
		},
		{
			MethodName: "ListControllers",
			Handler:    _ControllerRoutingService_ListControllers_Handler,
		},
		{
			MethodName: "ListClientsByController",
			Handler:    _ControllerRoutingService_ListClientsByController_Handler,
		},
		{
			MethodName: "GetAllRegistryData",
			Handler:    _ControllerRoutingService_GetAllRegistryData_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ControllerRoutingService_HealthCheck_Handler,
		},
		{
			MethodName: "NotifyClientDisconnected",
			Handler:    _ControllerRoutingService_NotifyClientDisconnected_Handler,
		},
		{
			MethodName: "DeleteController",
			Handler:    _ControllerRoutingService_DeleteController_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/registry.proto",
}

const (
	EnvoyRoutingService_RegisterControlPlane_FullMethodName    = "/bridge.EnvoyRoutingService/RegisterControlPlane"
	EnvoyRoutingService_GetControlPlaneCluster_FullMethodName  = "/bridge.EnvoyRoutingService/GetControlPlaneCluster"
	EnvoyRoutingService_NotifySnapshotDelivered_FullMethodName = "/bridge.EnvoyRoutingService/NotifySnapshotDelivered"
	EnvoyRoutingService_UpdateNodeList_FullMethodName          = "/bridge.EnvoyRoutingService/UpdateNodeList"
	EnvoyRoutingService_ListControlPlanes_FullMethodName       = "/bridge.EnvoyRoutingService/ListControlPlanes"
	EnvoyRoutingService_ListNodesByControlPlane_FullMethodName = "/bridge.EnvoyRoutingService/ListNodesByControlPlane"
	EnvoyRoutingService_GetAllRegistryData_FullMethodName      = "/bridge.EnvoyRoutingService/GetAllRegistryData"
	EnvoyRoutingService_HealthCheck_FullMethodName             = "/bridge.EnvoyRoutingService/HealthCheck"
	EnvoyRoutingService_DeleteControlPlane_FullMethodName      = "/bridge.EnvoyRoutingService/DeleteControlPlane"
)

// EnvoyRoutingServiceClient is the client API for EnvoyRoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Envoy Routing Service
type EnvoyRoutingServiceClient interface {
	RegisterControlPlane(ctx context.Context, in *RegisterControlPlaneRequest, opts ...grpc.CallOption) (*RegisterControlPlaneResponse, error)
	GetControlPlaneCluster(ctx context.Context, in *GetControlPlaneClusterRequest, opts ...grpc.CallOption) (*GetControlPlaneClusterResponse, error)
	// Control-plane snapshot verdi notification
	NotifySnapshotDelivered(ctx context.Context, in *NotifySnapshotDeliveredRequest, opts ...grpc.CallOption) (*NotifySnapshotDeliveredResponse, error)
	// Bulk node update (30sn'de bir)
	UpdateNodeList(ctx context.Context, in *UpdateNodeListRequest, opts ...grpc.CallOption) (*UpdateNodeListResponse, error)
	// List all control planes
	ListControlPlanes(ctx context.Context, in *ListControlPlanesRequest, opts ...grpc.CallOption) (*ListControlPlanesResponse, error)
	// List nodes by control plane
	ListNodesByControlPlane(ctx context.Context, in *ListNodesByControlPlaneRequest, opts ...grpc.CallOption) (*ListNodesByControlPlaneResponse, error)
	// Get all registry data for reporting
	GetAllRegistryData(ctx context.Context, in *GetAllRegistryDataRequest, opts ...grpc.CallOption) (*GetAllRegistryDataResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *EnvoyHealthCheckRequest, opts ...grpc.CallOption) (*EnvoyHealthCheckResponse, error)
	// Delete control plane
	DeleteControlPlane(ctx context.Context, in *DeleteControlPlaneRequest, opts ...grpc.CallOption) (*DeleteControlPlaneResponse, error)
}

type envoyRoutingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvoyRoutingServiceClient(cc grpc.ClientConnInterface) EnvoyRoutingServiceClient {
	return &envoyRoutingServiceClient{cc}
}

func (c *envoyRoutingServiceClient) RegisterControlPlane(ctx context.Context, in *RegisterControlPlaneRequest, opts ...grpc.CallOption) (*RegisterControlPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterControlPlaneResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_RegisterControlPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) GetControlPlaneCluster(ctx context.Context, in *GetControlPlaneClusterRequest, opts ...grpc.CallOption) (*GetControlPlaneClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetControlPlaneClusterResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_GetControlPlaneCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) NotifySnapshotDelivered(ctx context.Context, in *NotifySnapshotDeliveredRequest, opts ...grpc.CallOption) (*NotifySnapshotDeliveredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifySnapshotDeliveredResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_NotifySnapshotDelivered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) UpdateNodeList(ctx context.Context, in *UpdateNodeListRequest, opts ...grpc.CallOption) (*UpdateNodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeListResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_UpdateNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) ListControlPlanes(ctx context.Context, in *ListControlPlanesRequest, opts ...grpc.CallOption) (*ListControlPlanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListControlPlanesResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_ListControlPlanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) ListNodesByControlPlane(ctx context.Context, in *ListNodesByControlPlaneRequest, opts ...grpc.CallOption) (*ListNodesByControlPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesByControlPlaneResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_ListNodesByControlPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) GetAllRegistryData(ctx context.Context, in *GetAllRegistryDataRequest, opts ...grpc.CallOption) (*GetAllRegistryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRegistryDataResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_GetAllRegistryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) HealthCheck(ctx context.Context, in *EnvoyHealthCheckRequest, opts ...grpc.CallOption) (*EnvoyHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvoyHealthCheckResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyRoutingServiceClient) DeleteControlPlane(ctx context.Context, in *DeleteControlPlaneRequest, opts ...grpc.CallOption) (*DeleteControlPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteControlPlaneResponse)
	err := c.cc.Invoke(ctx, EnvoyRoutingService_DeleteControlPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvoyRoutingServiceServer is the server API for EnvoyRoutingService service.
// All implementations must embed UnimplementedEnvoyRoutingServiceServer
// for forward compatibility.
//
// Envoy Routing Service
type EnvoyRoutingServiceServer interface {
	RegisterControlPlane(context.Context, *RegisterControlPlaneRequest) (*RegisterControlPlaneResponse, error)
	GetControlPlaneCluster(context.Context, *GetControlPlaneClusterRequest) (*GetControlPlaneClusterResponse, error)
	// Control-plane snapshot verdi notification
	NotifySnapshotDelivered(context.Context, *NotifySnapshotDeliveredRequest) (*NotifySnapshotDeliveredResponse, error)
	// Bulk node update (30sn'de bir)
	UpdateNodeList(context.Context, *UpdateNodeListRequest) (*UpdateNodeListResponse, error)
	// List all control planes
	ListControlPlanes(context.Context, *ListControlPlanesRequest) (*ListControlPlanesResponse, error)
	// List nodes by control plane
	ListNodesByControlPlane(context.Context, *ListNodesByControlPlaneRequest) (*ListNodesByControlPlaneResponse, error)
	// Get all registry data for reporting
	GetAllRegistryData(context.Context, *GetAllRegistryDataRequest) (*GetAllRegistryDataResponse, error)
	// Health check
	HealthCheck(context.Context, *EnvoyHealthCheckRequest) (*EnvoyHealthCheckResponse, error)
	// Delete control plane
	DeleteControlPlane(context.Context, *DeleteControlPlaneRequest) (*DeleteControlPlaneResponse, error)
	mustEmbedUnimplementedEnvoyRoutingServiceServer()
}

// UnimplementedEnvoyRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvoyRoutingServiceServer struct{}

func (UnimplementedEnvoyRoutingServiceServer) RegisterControlPlane(context.Context, *RegisterControlPlaneRequest) (*RegisterControlPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterControlPlane not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) GetControlPlaneCluster(context.Context, *GetControlPlaneClusterRequest) (*GetControlPlaneClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControlPlaneCluster not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) NotifySnapshotDelivered(context.Context, *NotifySnapshotDeliveredRequest) (*NotifySnapshotDeliveredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifySnapshotDelivered not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) UpdateNodeList(context.Context, *UpdateNodeListRequest) (*UpdateNodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeList not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) ListControlPlanes(context.Context, *ListControlPlanesRequest) (*ListControlPlanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListControlPlanes not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) ListNodesByControlPlane(context.Context, *ListNodesByControlPlaneRequest) (*ListNodesByControlPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodesByControlPlane not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) GetAllRegistryData(context.Context, *GetAllRegistryDataRequest) (*GetAllRegistryDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRegistryData not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) HealthCheck(context.Context, *EnvoyHealthCheckRequest) (*EnvoyHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) DeleteControlPlane(context.Context, *DeleteControlPlaneRequest) (*DeleteControlPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteControlPlane not implemented")
}
func (UnimplementedEnvoyRoutingServiceServer) mustEmbedUnimplementedEnvoyRoutingServiceServer() {}
func (UnimplementedEnvoyRoutingServiceServer) testEmbeddedByValue()                             {}

// UnsafeEnvoyRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvoyRoutingServiceServer will
// result in compilation errors.
type UnsafeEnvoyRoutingServiceServer interface {
	mustEmbedUnimplementedEnvoyRoutingServiceServer()
}

func RegisterEnvoyRoutingServiceServer(s grpc.ServiceRegistrar, srv EnvoyRoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnvoyRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvoyRoutingService_ServiceDesc, srv)
}

func _EnvoyRoutingService_RegisterControlPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterControlPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).RegisterControlPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_RegisterControlPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).RegisterControlPlane(ctx, req.(*RegisterControlPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_GetControlPlaneCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetControlPlaneClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).GetControlPlaneCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_GetControlPlaneCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).GetControlPlaneCluster(ctx, req.(*GetControlPlaneClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_NotifySnapshotDelivered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifySnapshotDeliveredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).NotifySnapshotDelivered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_NotifySnapshotDelivered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).NotifySnapshotDelivered(ctx, req.(*NotifySnapshotDeliveredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_UpdateNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).UpdateNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_UpdateNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).UpdateNodeList(ctx, req.(*UpdateNodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_ListControlPlanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListControlPlanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).ListControlPlanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_ListControlPlanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).ListControlPlanes(ctx, req.(*ListControlPlanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_ListNodesByControlPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesByControlPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).ListNodesByControlPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_ListNodesByControlPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).ListNodesByControlPlane(ctx, req.(*ListNodesByControlPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_GetAllRegistryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRegistryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).GetAllRegistryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_GetAllRegistryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).GetAllRegistryData(ctx, req.(*GetAllRegistryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvoyHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).HealthCheck(ctx, req.(*EnvoyHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyRoutingService_DeleteControlPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteControlPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyRoutingServiceServer).DeleteControlPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyRoutingService_DeleteControlPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyRoutingServiceServer).DeleteControlPlane(ctx, req.(*DeleteControlPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvoyRoutingService_ServiceDesc is the grpc.ServiceDesc for EnvoyRoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvoyRoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.EnvoyRoutingService",
	HandlerType: (*EnvoyRoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterControlPlane",
			Handler:    _EnvoyRoutingService_RegisterControlPlane_Handler,
		},
		{
			MethodName: "GetControlPlaneCluster",
			Handler:    _EnvoyRoutingService_GetControlPlaneCluster_Handler,
		},
		{
			MethodName: "NotifySnapshotDelivered",
			Handler:    _EnvoyRoutingService_NotifySnapshotDelivered_Handler,
		},
		{
			MethodName: "UpdateNodeList",
			Handler:    _EnvoyRoutingService_UpdateNodeList_Handler,
		},
		{
			MethodName: "ListControlPlanes",
			Handler:    _EnvoyRoutingService_ListControlPlanes_Handler,
		},
		{
			MethodName: "ListNodesByControlPlane",
			Handler:    _EnvoyRoutingService_ListNodesByControlPlane_Handler,
		},
		{
			MethodName: "GetAllRegistryData",
			Handler:    _EnvoyRoutingService_GetAllRegistryData_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _EnvoyRoutingService_HealthCheck_Handler,
		},
		{
			MethodName: "DeleteControlPlane",
			Handler:    _EnvoyRoutingService_DeleteControlPlane_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/registry.proto",
}
