package shield

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path"
	"sort"

	"github.com/CloudNativeWorks/elchi-backend/pkg/models"
)

// ClearMarkerFile is the reserved file name of the auto-generated "true clear"
// config. elchi-shield deliberately keeps its last-good snapshot when its config
// directory empties (safety against accidental deletion), so an empty bundle would
// leave the edge ENFORCING the old config. Instead, an empty policy set renders
// this one explicit mode-off config: shield loads it (the active version changes,
// so the reload confirms fast and honestly) and inspection genuinely stops.
// The name is reserved — crud.validate rejects user files with it.
const ClearMarkerFile = "00-elchi-default.yaml"

// clearMarkerContent is the marker's body: a valid zero-domain SecurityPolicy with
// an explicit off default ("off" quoted so no YAML dialect reads it as a boolean).
var clearMarkerContent = []byte(`# Auto-generated by Elchi: this project's shield policy set is empty.
# Explicitly disables inspection (a true "clear") while keeping elchi-shield's
# empty-directory keep-last-good safety intact. Do not edit; any policy create
# replaces this file.
apiVersion: sentinel.elchi.io/v1
kind: SecurityPolicy
spec:
  defaults:
    mode: "off"
`)

// MergePolicies folds all of a project's policies into a single full-sync config
// bundle (the complete desired state the edge mirrors). File paths must be unique
// across policies (collisions are rejected, though crud.collisionCheck prevents
// storing them in the first place). The bundle Version is a deterministic digest of
// the merged content, so the edge's active_config_version changes iff the content
// does. An empty policy set yields a full-sync bundle holding only the clear
// marker (see ClearMarkerFile) — never an empty directory.
func MergePolicies(policies []ShieldPolicy) (models.ShieldConfigJSON, error) {
	ordered := make([]ShieldPolicy, len(policies))
	copy(ordered, policies)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })

	cfg := models.ShieldConfigJSON{FullSync: true}
	owner := make(map[string]string)
	for pi := range ordered {
		for fi := range ordered[pi].Files {
			f := ordered[pi].Files[fi]
			clean := path.Clean(f.Path)
			if prev, clash := owner[clean]; clash {
				return cfg, fmt.Errorf("file path %q is defined by both policy %q and %q", clean, prev, ordered[pi].Name)
			}
			owner[clean] = ordered[pi].Name
			cfg.Files = append(cfg.Files, f)
		}
	}

	if len(cfg.Files) == 0 {
		cfg.Files = append(cfg.Files, models.ShieldFileJSON{
			Path:    ClearMarkerFile,
			Content: clearMarkerContent,
			Mode:    "0640",
		})
	}

	// Deterministic version: hash the sorted (path, effective-sha256) pairs.
	sort.Slice(cfg.Files, func(i, j int) bool { return cfg.Files[i].Path < cfg.Files[j].Path })
	h := sha256.New()
	for i := range cfg.Files {
		f := cfg.Files[i]
		eff := f.Sha256
		if eff == "" {
			sum := sha256.Sum256(f.Content)
			eff = hex.EncodeToString(sum[:])
		}
		_, _ = h.Write([]byte(f.Path))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write([]byte(eff))
		_, _ = h.Write([]byte{0})
	}
	cfg.Version = hex.EncodeToString(h.Sum(nil))[:12]
	return cfg, nil
}
