package waf

import (
	"embed"
	"strings"
	"sync"
)

// shieldCRSFS holds the SHIELD CRS rule libraries — keyed by the coraza-coreruleset
// module version the elchi-shield binary embeds (e.g. v4.25.0), NOT the WASM path's
// OWASP CRS semver (4.14.0, embedded.go — untouched). Generated by
// scripts/parse_coraza_rules.py --rules-dir <coreruleset @owasp_crs> --crs-version <ver>.
//
//go:embed data/crs_rules_coreruleset_*.json
var shieldCRSFS embed.FS

type shieldCRSEntry struct {
	Rules    []byte
	Metadata []byte
}

var (
	shieldCRSOnce      sync.Once
	shieldCRSByVersion map[string]shieldCRSEntry
)

// loadShieldCRS discovers the embedded shield CRS files ONCE. Adding a new coreruleset
// version is therefore just committing a generated crs_rules_coreruleset_<ver>.json
// (+ _metadata.json) — no code change (Phase 2 goal, already satisfied here).
func loadShieldCRS() {
	shieldCRSByVersion = map[string]shieldCRSEntry{}
	entries, err := shieldCRSFS.ReadDir("data")
	if err != nil {
		return
	}
	const prefix = "crs_rules_coreruleset_"
	for _, e := range entries {
		name := e.Name()
		if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, ".json") || strings.HasSuffix(name, "_metadata.json") {
			continue
		}
		version := strings.TrimSuffix(strings.TrimPrefix(name, prefix), ".json")
		rules, err := shieldCRSFS.ReadFile("data/" + name)
		if err != nil {
			continue
		}
		meta, _ := shieldCRSFS.ReadFile("data/" + prefix + version + "_metadata.json")
		shieldCRSByVersion[version] = shieldCRSEntry{Rules: rules, Metadata: meta}
	}
}

// ShieldCRSVersions returns the coreruleset versions the backend ships a shield rule
// library for.
func ShieldCRSVersions() []string {
	shieldCRSOnce.Do(loadShieldCRS)
	out := make([]string, 0, len(shieldCRSByVersion))
	for v := range shieldCRSByVersion {
		out = append(out, v)
	}
	return out
}

// ShieldCRSData returns the raw rules + metadata JSON for a coreruleset version, or
// ok=false when the backend has no library for it (a shield binary newer than the
// backend's generated set).
func ShieldCRSData(version string) (rules, metadata []byte, ok bool) {
	shieldCRSOnce.Do(loadShieldCRS)
	e, ok := shieldCRSByVersion[version]
	return e.Rules, e.Metadata, ok
}
