package catalog

import "github.com/CloudNativeWorks/elchi-backend/pkg/models"

// HttpConnectionManagerDefinition defines the HTTP connection manager component
var HttpConnectionManagerDefinition = models.ComponentDefinition{
	Name:          "http_connection_manager",
	Label:         "HTTP Connection Manager",
	Description:   "HTTP filter that manages HTTP/1.1, HTTP/2, and HTTP/3 connections",
	Category:      "envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
	Collection:    "filters",
	CanonicalName: "envoy.filters.network.http_connection_manager",
	GType:         "envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
	Priority:      500,
	AvailableFields: []models.AvailableField{
		{
			Name:                 "stat_prefix",
			Label:                "Statistics Prefix",
			Description:          "Prefix for HTTP statistics emitted by this filter",
			Type:                 models.FieldTypeString,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			ValidationRules:      []string{"required"},
		},
		{
			Name:                 "codec_type",
			Label:                "HTTP Codec Type",
			Description:          "HTTP protocol version to use",
			Type:                 models.FieldTypeSelect,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			DefaultValue:         "AUTO",
			Options: []models.FieldOption{
				{Value: "AUTO", Label: "AUTO - Detect automatically"},
				{Value: "HTTP1", Label: "HTTP/1.1"},
				{Value: "HTTP2", Label: "HTTP/2"},
				{Value: "HTTP3", Label: "HTTP/3"},
			},
		},
		{
			Name:                 "route_configuration",
			Label:                "Route Configuration",
			Description:          "Choose how to configure routing for this HCM",
			Type:                 models.FieldTypeNestedChoice,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			NestedConfig: &models.NestedFieldConfig{
				MutuallyExclusive: true,
				DefaultChoice:     "rds",
				Choices: []models.ConditionalChoice{
					{
						Value: "rds",
						Label: "RDS (Route Discovery Service)",
						SubFields: []models.AvailableField{
							{
								Name:                 "route_config_name",
								Label:                "Route Configuration Name",
								Description:          "Select route configuration from scenario or system",
								Type:                 models.FieldTypeSelect,
								RequiredForCreation:  true,
								RequiredForExecution: true,
								Connected: &models.ConnectedField{
									ComponentTypes: []string{"route"},
									FieldName:      "name",
								},
								ApiEndpoint:       "/api/v3/custom/resource_list?collection=routes&type=routes",
								UseApiAndScenario: true,
								ValidationRules:   []string{"required", "route_exists"},
							},
						},
					},
					{
						Value: "inline",
						Label: "Inline Route Configuration",
						SubFields: []models.AvailableField{
							{
								Name:                 "name",
								Label:                "Route Config Name",
								Description:          "Name for the inline route configuration",
								Type:                 models.FieldTypeString,
								RequiredForCreation:  true,
								RequiredForExecution: true,
							},
							{
								Name:                 "virtual_host_config",
								Label:                "Virtual Host Configuration",
								Description:          "Choose how to configure virtual hosts",
								Type:                 models.FieldTypeNestedChoice,
								RequiredForCreation:  true,
								RequiredForExecution: true,
								NestedConfig: &models.NestedFieldConfig{
									MutuallyExclusive: true,
									DefaultChoice:     "vhds",
									Choices: []models.ConditionalChoice{
										{
											Value: "vhds",
											Label: "VHDS (Virtual Host Discovery Service)",
											SubFields: []models.AvailableField{
												{
													Name:                 "vhds_config_source",
													Label:                "VHDS Config Source",
													Description:          "VHDS configuration source",
													Type:                 models.FieldTypeSelect,
													RequiredForCreation:  true,
													RequiredForExecution: true,
													ApiEndpoint:          "/api/v3/custom/resource_list?collection=virtual_hosts&type=virtual_hosts",
													HasMetadata:          true,
													Connected: &models.ConnectedField{
														ComponentTypes: []string{"virtual_host"},
														FieldName:      ":componentname:",
													},
												},
											},
										},
										{
											Value: "inline_virtual_hosts",
											Label: "Inline Virtual Hosts",
											SubFields: []models.AvailableField{
												{
													Name:                 "virtual_hosts",
													Label:                "Virtual Hosts List",
													Description:          "Define virtual hosts inline",
													Type:                 models.FieldTypeArray,
													RequiredForCreation:  true,
													RequiredForExecution: true,
													ArraySchema: &models.ArraySchema{
														ItemType: models.FieldTypeObject,
														Properties: map[string]models.FieldDef{
															"name": {
																Type:     models.FieldTypeString,
																Label:    "Virtual Host Name",
																Required: true,
															},
															"domains": {
																Type:         models.FieldTypeArray,
																Label:        "Domains",
																Required:     true,
																DefaultValue: []string{"*"},
															},
															"routes": {
																Type:     models.FieldTypeArray,
																Label:    "Routes",
																Required: true,
																Properties: map[string]models.FieldDef{
																	"match_type": {
																		Type:         models.FieldTypeSelect,
																		Label:        "Match Type",
																		Required:     true,
																		DefaultValue: "prefix",
																		Options: []models.FieldOption{
																			{Value: "prefix", Label: "Prefix Match"},
																			{Value: "path", Label: "Exact Path Match"},
																			{Value: "safe_regex", Label: "Regex Match"},
																		},
																	},
																	"match_value": {
																		Type:         models.FieldTypeString,
																		Label:        "Match Value",
																		Required:     true,
																		DefaultValue: "/",
																	},
																	"route_cluster": {
																		Type:        models.FieldTypeSelect,
																		Label:       "Target Cluster",
																		Description: "Select cluster from scenario components",
																		Required:    true,
																		Connected: &models.ConnectedField{
																			ComponentTypes: []string{"cluster"},
																			FieldName:      "name",
																		},
																	},
																	"timeout": {
																		Type:         models.FieldTypeString,
																		Label:        "Route Timeout",
																		Required:     false,
																		DefaultValue: "15s",
																	},
																},
															},
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			Name:                 "http_filters",
			Label:                "HTTP Filters",
			Description:          "HTTP filters for request/response processing",
			Type:                 models.FieldTypeArray,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			ApiEndpoint:          "/api/v3/custom/http_filter_list?collection=filters&category=envoy.filters.http",
			HasMetadata:          true,
			UseApiAndScenario:    true,
			Connected: &models.ConnectedField{
				ComponentTypes: []string{"router_filter", "cors_filter", "rbac_filter", "basic_auth_filter", "rate_limit_filter"},
				FieldName:      ":componentname:",
			},
			ValidationRules: []string{"required", "required_router_filter"},
		},
	{
		Name:                 "add_user_agent",
		Label:                "Add User Agent",
		Description:          "Whether to add user agent header",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         true,
	},
	{
		Name:                 "server_name",
		Label:                "Server Name", 
		Description:          "Server name for HTTP response headers",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
	},
	{
		Name:                 "server_header_transformation",
		Label:                "Server Header Transformation",
		Description:          "How to transform the server header",
		Type:                 models.FieldTypeSelect,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         "OVERWRITE",
		Options: []models.FieldOption{
			{Value: "OVERWRITE", Label: "Overwrite"},
			{Value: "APPEND_IF_ABSENT", Label: "Append If Absent"},
			{Value: "PASS_THROUGH", Label: "Pass Through"},
		},
	},
	{
		Name:                 "max_request_headers_kb",
		Label:                "Max Request Headers KB",
		Description:          "Maximum size of request headers in KB",
		Type:                 models.FieldTypeInt,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         60,
	},
	{
		Name:                 "stream_idle_timeout",
		Label:                "Stream Idle Timeout",
		Description:          "Stream idle timeout duration",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		ValidationRules:      []string{"duration"},
	},
	{
		Name:                 "request_timeout",
		Label:                "Request Timeout",
		Description:          "Request timeout duration",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		ValidationRules:      []string{"duration"},
	},
	{
		Name:                 "request_headers_timeout",
		Label:                "Request Headers Timeout",
		Description:          "Request headers timeout duration",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		ValidationRules:      []string{"duration"},
	},
	{
		Name:                 "delayed_close_timeout",
		Label:                "Delayed Close Timeout",
		Description:          "Delayed close timeout duration",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		ValidationRules:      []string{"duration"},
	},
	{
		Name:                 "use_remote_address",
		Label:                "Use Remote Address",
		Description:          "Whether to use remote address for X-Forwarded-For",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         false,
	},
	{
		Name:                 "skip_xff_append",
		Label:                "Skip XFF Append",
		Description:          "Whether to skip appending to X-Forwarded-For header",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         false,
	},
	{
		Name:                 "via",
		Label:                "Via Header Value",
		Description:          "Value for Via header",
		Type:                 models.FieldTypeString,
		RequiredForCreation:  false,
		RequiredForExecution: false,
	},
	{
		Name:                 "generate_request_id",
		Label:                "Generate Request ID",
		Description:          "Whether to generate request ID",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         true,
	},
	{
		Name:                 "proxy_100_continue",
		Label:                "Proxy 100 Continue",
		Description:          "Whether to proxy 100-continue responses",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         false,
	},
	{
		Name:                 "enable_http2_protocol_options",
		Label:                "Enable HTTP/2 Protocol Options",
		Description:          "Enable HTTP/2 protocol configuration",
		Type:                 models.FieldTypeBool,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		DefaultValue:         false,
	},
	{
		Name:                 "access_log",
		Label:                "Access Log Configuration",
		Description:          "Configure access logging for HTTP requests",
		Type:                 models.FieldTypeSelect,
		RequiredForCreation:  false,
		RequiredForExecution: false,
		ApiEndpoint:          "/api/v3/custom/resource_list?collection=extensions&category=envoy.access_loggers",
		HasMetadata:          true,
	},
	},
	Rules: models.ComponentRule{
		ConflictWith: []string{"tcp_proxy"}, // Cannot coexist with TCP proxy on same listener
		MinCount:     0,
		MaxCount:     10,
		// No field conflicts needed - nested choices handle mutual exclusivity
	},
}
