package catalog

import "github.com/CloudNativeWorks/elchi-backend/pkg/models"

// ListenerDefinition defines the listener component
var ListenerDefinition = models.ComponentDefinition{
	Name:          "listener",
	Label:         "Listener Configuration",
	Description:   "Network listener that receives incoming connections",
	Category:      "envoy.config.listener.v3.Listener",
	Collection:    "listeners",
	CanonicalName: "config.listener.v3.Listener",
	GType:         "envoy.config.listener.v3.Listener",
	Priority:      999,
	AvailableFields: []models.AvailableField{
		{
			Name:                 "name",
			Label:                "Listener Name",
			Description:          "Unique name for the listener",
			Type:                 models.FieldTypeString,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			ValidationRules:      []string{"required", "unique"},
		},
		{
			Name:                 "address",
			Label:                "Bind Address",
			Description:          "IP address to bind the listener to",
			Type:                 models.FieldTypeString,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			DefaultValue:         "0.0.0.0",
			ValidationRules:      []string{"required", "ipv4"},
		},
		{
			Name:                 "port",
			Label:                "Port",
			Description:          "Port number to listen on",
			Type:                 models.FieldTypeInt,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			ValidationRules:      []string{"required", "port"},
		},
		{
			Name:                 "protocol",
			Label:                "Protocol",
			Description:          "Network protocol",
			Type:                 models.FieldTypeSelect,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			DefaultValue:         "TCP",
			Options: []models.FieldOption{
				{Value: "TCP", Label: "TCP"},
				{Value: "UDP", Label: "UDP"},
			},
		},
		{
			Name:                 "network_filters",
			Label:                "Network Filters",
			Description:          "Network filters for this listener (HCM, TCP Proxy, Connection Limit, etc.)",
			Type:                 models.FieldTypeArray,
			RequiredForCreation:  true,
			RequiredForExecution: true,
			ApiEndpoint:          "/api/v3/custom/resource_list_search?collection=filters&category=envoy.filters.network",
			HasMetadata:          true,
			UseInScenario:        true,
			UseApi:               true,
			Connected: &models.ConnectedField{
				ComponentTypes: []string{"http_connection_manager", "tcp_proxy", "connection_limit", "local_ratelimit", "rbac"},
				FieldName:      ":componentname:",
			},
			ValidationRules: []string{}, // Validation is handled at component level
		},
		{
			Name:                 "stat_prefix",
			Label:                "Statistics Prefix",
			Description:          "Prefix for statistics emitted by this listener",
			Type:                 models.FieldTypeString,
			RequiredForCreation:  false,
			RequiredForExecution: false,
		},
		{
			Name:                 "use_original_dst",
			Label:                "Use Original Destination",
			Description:          "Use SO_ORIGINAL_DST socket option to get original destination",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "per_connection_buffer_limit_bytes",
			Label:                "Per Connection Buffer Limit",
			Description:          "Maximum buffer size per connection in bytes",
			Type:                 models.FieldTypeInt,
			RequiredForCreation:  false,
			RequiredForExecution: false,
		},
		{
			Name:                 "continue_on_listener_filters_timeout",
			Label:                "Continue on Listener Filters Timeout",
			Description:          "Continue processing if listener filters timeout",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "transparent",
			Label:                "Transparent Mode",
			Description:          "Enable transparent mode for this listener",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "freebind",
			Label:                "Freebind",
			Description:          "Enable IP_FREEBIND socket option",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "tcp_fast_open_queue_length",
			Label:                "TCP Fast Open Queue Length",
			Description:          "TCP Fast Open queue length",
			Type:                 models.FieldTypeInt,
			RequiredForCreation:  false,
			RequiredForExecution: false,
		},
		{
			Name:                 "traffic_direction",
			Label:                "Traffic Direction",
			Description:          "Traffic direction for this listener",
			Type:                 models.FieldTypeSelect,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         "UNSPECIFIED",
			Options: []models.FieldOption{
				{Value: "UNSPECIFIED", Label: "Unspecified"},
				{Value: "INBOUND", Label: "Inbound"},
				{Value: "OUTBOUND", Label: "Outbound"},
			},
		},
		{
			Name:                 "tls_ssl_config",
			Label:                "TLS/SSL Configuration",
			Description:          "Configure TLS/SSL settings and additional HTTP listener options",
			Type:                 models.FieldTypeNestedChoice,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			NestedConfig: &models.NestedFieldConfig{
				MutuallyExclusive: true,
				DefaultChoice:     "",
				Choices: []models.ConditionalChoice{
					{
						Value: "enable_tls",
						Label: "Enable TLS/SSL",
						SubFields: []models.AvailableField{
							{
								Name:                 "downstream_tls",
								Label:                "Downstream TLS Context",
								Description:          "TLS context for incoming connections",
								Type:                 models.FieldTypeSelect,
								RequiredForCreation:  true,
								RequiredForExecution: true,
								ApiEndpoint:          "/api/v3/custom/resource_list_search?collection=tls&gtype=envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
								HasMetadata:          true,
								ValidationRules:      []string{"required"},
							},
							{
								Name:                 "http_listener_config",
								Label:                "HTTP Listener Options",
								Description:          "Additional HTTP listener configuration options",
								Type:                 models.FieldTypeNestedChoice,
								RequiredForCreation:  false,
								RequiredForExecution: false,
								NestedConfig: &models.NestedFieldConfig{
									MutuallyExclusive: true,
									DefaultChoice:     "",
									Choices: []models.ConditionalChoice{
										{
											Value: "redirect",
											Label: "Create HTTP to HTTPS Redirect Listener",
											SubFields: []models.AvailableField{
												{
													Name:                 "http_port",
													Label:                "HTTP Port",
													Description:          "Port for HTTP redirect listener",
													Type:                 models.FieldTypeInt,
													RequiredForCreation:  true,
													RequiredForExecution: true,
													DefaultValue:         80,
													ValidationRules:      []string{"required", "port"},
												},
											},
										},
										{
											Value: "create_http_listener",
											Label: "Create Additional HTTP Listener",
											SubFields: []models.AvailableField{
												{
													Name:                 "http_port",
													Label:                "HTTP Port",
													Description:          "Port for additional HTTP listener",
													Type:                 models.FieldTypeInt,
													RequiredForCreation:  true,
													RequiredForExecution: true,
													DefaultValue:         8080,
													ValidationRules:      []string{"required", "port"},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			Name:                 "enable_reuse_port",
			Label:                "Enable Reuse Port",
			Description:          "Enable SO_REUSEPORT socket option",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "tcp_backlog_size",
			Label:                "TCP Backlog Size",
			Description:          "TCP listen backlog size",
			Type:                 models.FieldTypeInt,
			RequiredForCreation:  false,
			RequiredForExecution: false,
		},
		{
			Name:                 "max_connections_to_accept_per_socket_event",
			Label:                "Max Connections Per Socket Event",
			Description:          "Maximum connections to accept per socket event",
			Type:                 models.FieldTypeInt,
			RequiredForCreation:  false,
			RequiredForExecution: false,
		},
		{
			Name:                 "bind_to_port",
			Label:                "Bind to Port",
			Description:          "Whether to bind to the port",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         true,
		},
		{
			Name:                 "ignore_global_conn_limit",
			Label:                "Ignore Global Connection Limit",
			Description:          "Ignore global connection limit for this listener",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
		{
			Name:                 "bypass_overload_manager",
			Label:                "Bypass Overload Manager",
			Description:          "Bypass overload manager for this listener",
			Type:                 models.FieldTypeBool,
			RequiredForCreation:  false,
			RequiredForExecution: false,
			DefaultValue:         false,
		},
	},
	Rules: models.ComponentRule{
		MinCount:                    1,
		MaxCount:                    50,
		ValidationRulesForCreation:  []string{"listener_filter_requirement"},
		ValidationRulesForExecution: []string{}, // Same rule applies to both contexts
	},
}
