ELCHI_ADDRESS: "${ELCHI_ADDRESS}"
ELCHI_PORT: "${ELCHI_PORT}"
ELCHI_TLS_ENABLED: "${ELCHI_TLS_ENABLED}"
ELCHI_GRPC_NODE_COUNT: "${ELCHI_GRPC_NODE_COUNT}"
ELCHI_REST_NODE_COUNT: "${ELCHI_REST_NODE_COUNT}"
ELCHI_ENABLE_DEMO: "${ELCHI_ENABLE_DEMO}"
ELCHI_INTERNAL_COMMUNICATION: "false"
ELCHI_INTERNAL_ADDRESS_PORT: "envoy-service.elchi-platform.svc.cluster.local:8080"
ELCHI_VERSIONS:
  - v1.32.3
  - v1.33.2
MONGODB_HOSTS: "${MONGODB_HOSTS}"
MONGODB_USERNAME: "${MONGODB_USERNAME}"
MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
MONGODB_DATABASE: "${MONGODB_DATABASE}"
MONGODB_SCHEME: "${MONGODB_SCHEME}"
MONGODB_PORT: ""
MONGODB_REPLICASET: ""
MONGODB_TIMEOUTMS: "${MONGODB_TIMEOUTMS}"
MONGODB_TLS_ENABLED: "${MONGODB_TLS_ENABLED}"

LOG_LEVEL: debug # debug, info, warn, error
LOG_FORMATTER: text # json, text
LOG_REPORTCALLER: "false"

SMTP_PASSWORD: "${SMTP_PASSWORD}"
